#!/usr/bin/env python3

from colorama import Fore, Style, init
import requests

# Initialize colors
init(autoreset=True)

# Banner
print(Fore.CYAN + r"""

   
  /$$$$$$  /$$       /$$$$$$ /$$    /$$ /$$$$$$$$        /$$$$$$  /$$   /$$ /$$$$$$$$  /$$$$$$  /$$   /$$ /$$$$$$$$ /$$$$$$$ 
 /$$__  $$| $$      |_  $$_/| $$   | $$| $$_____/       /$$__  $$| $$  | $$| $$_____/ /$$__  $$| $$  /$$/| $$_____/| $$__  $$
| $$  \ $$| $$        | $$  | $$   | $$| $$            | $$  \__/| $$  | $$| $$      | $$  \__/| $$ /$$/ | $$      | $$  \ $$
| $$$$$$$$| $$        | $$  |  $$ / $$/| $$$$$         | $$      | $$$$$$$$| $$$$$   | $$      | $$$$$/  | $$$$$   | $$$$$$$/
| $$__  $$| $$        | $$   \  $$ $$/ | $$__/         | $$      | $$__  $$| $$__/   | $$      | $$  $$  | $$__/   | $$__  $$
| $$  | $$| $$        | $$    \  $$$/  | $$            | $$    $$| $$  | $$| $$      | $$    $$| $$\  $$ | $$      | $$  \ $$
| $$  | $$| $$$$$$$$ /$$$$$$   \  $/   | $$$$$$$$      |  $$$$$$/| $$  | $$| $$$$$$$$|  $$$$$$/| $$ \  $$| $$$$$$$$| $$  | $$
|__/  |__/|________/|______/    \_/    |________/       \______/ |__/  |__/|________/ \______/ |__/  \__/|________/|__/  |__/

""" + Style.RESET_ALL)

alive_count = 0


def alive_checker(site):

    global alive_count

    try:

        headers = {
            "User-Agent": "Mozilla/5.0"
        }

        site = "https://" + site

        r = requests.get(site, headers=headers, timeout=3)

        if r.status_code == 200:

            alive_count += 1

            print(
                f"{Fore.GREEN}[200]{Style.RESET_ALL} ---> "
                f"{Fore.CYAN}{site}"
            )

            with open("alive.txt", "a") as f:

                f.write(site + "\n")

    except:
        pass


target_name = input(
    Fore.YELLOW + "ENTER FILE : " + Style.RESET_ALL
).strip()


with open(target_name) as arya:

    for line in arya:

        alive_checker(line.strip())


print(
    Fore.YELLOW +
    f"\nTOTAL ALIVE HOSTS : {alive_count}"
)
